version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DATABASE: test
    ports:
      - 5432:5432
  queue:
    image: rabbitmq:3.11.0-management
    hostname: streamer-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    ports:
      - 5672:5672
      - 15672:15672
